Algoritmo "funcao"
funcao CalcularSoma(a,b: inteiro):inteiro
var
   resultado:inteiro
inicio
   resultado <-a+b
   retorne resultado
fimfuncao
Var
   primeiroNumero, segundoNumero,soma: inteiro
Inicio

   escreva ("Digite o primeiro numero: ")
   leia(primeiroNumero)
   escreva ("Digite o segundo numero: ")
   leia(segundoNumero)

   soma<- CalcularSoma(primeiroNumero, segundoNumero)

   escreval ("A soma dos números é: ", soma)


Fimalgoritmo